INSERT INTO CATALOG_ENTITY (ID, TITLE, DESCRIPTION) VALUES (1, 'Title1', 'First forum description example');
INSERT INTO CATALOG_ENTITY (ID, TITLE, DESCRIPTION) VALUES (2, 'Title1', 'Second forum description example');
INSERT INTO CATALOG_ENTITY (ID, TITLE, DESCRIPTION) VALUES (4, 'Title2', 'dadwawdadwad');
INSERT INTO MOVIE_ENTITY (ID, TITLE, MOVIE_ID, INFO) VALUES (1, 'Post cool title', 1, 'INFO_1');
INSERT INTO MOVIE_ENTITY (ID, TITLE, MOVIE_ID, INFO) VALUES (2, 'Another post cool title', 1, 'INFO_2');
INSERT INTO MOVIE_ENTITY (ID, TITLE, MOVIE_ID, INFO) VALUES (3, 'Post cool title', 2, 'INFO_3');
INSERT INTO MOVIE_ENTITY (ID, TITLE, MOVIE_ID, INFO) VALUES (4, 'Another post cool title', 2, 'INFO_4');
INSERT INTO COMMENT_ENTITY (ID, POST_ID, AUTHOR, BODY) VALUES (1, 2, 'Andris', 'First comment!');