
INSERT INTO GROUP_ENTITY (ID , PROGRAMM ) VALUES ('4701BD', 'Programming');
INSERT INTO GROUP_ENTITY (ID , PROGRAMM ) VALUES ('4702BD', 'Electronic');



INSERT INTO PEOPLE (CODE , FIRSTNAME , SURNAME , GROUP_ID ) VALUES (1 , 'Oleg' , 'Gavrilov' , '4701BD');
INSERT INTO PEOPLE (CODE , FIRSTNAME , SURNAME , GROUP_ID ) VALUES (2 , 'Maksim' , 'Filimonov' , '4701BD');
INSERT INTO PEOPLE (CODE , FIRSTNAME , SURNAME , GROUP_ID ) VALUES (3 , 'Igorj' , 'Pirozkov' , '4701BD');

INSERT INTO PEOPLE (CODE , FIRSTNAME , SURNAME , GROUP_ID ) VALUES (4 , 'Andrej' , 'Petr' , '4702BD');
INSERT INTO PEOPLE (CODE , FIRSTNAME , SURNAME , GROUP_ID ) VALUES (5 , 'Marina' , 'Gergelizu' , '4702BD');
INSERT INTO PEOPLE (CODE , FIRSTNAME , SURNAME , GROUP_ID ) VALUES (6 , 'Nanila' , 'Poperecnij' , '4702BD');


INSERT INTO MARK (ID , MARK_VALUE , PUPIL_ID , SUBJECT  ) VALUES (1 , 10 , 1 , 'Math' );